# Pantheon Environment: (Updated 06/05/2018 - jthomas)
#     Operating System: redhat 4.14.11
#     Webserver: nginx/1.8.1
#     Php: 5.6.36
#     Drupal: 7.59
#     Redis: 2.8.23
#     DB: 5.5.5-10.0.23-MariaDB

version: '3'

services:
  mariadb:
    image: "jackthomasatl/docker-d8-mariadb:5.5"
    hostname: usbank-elavon-db
    ports:
      - "3306:3306" # mysql
    environment:
      - MYSQL_DATABASE=elavon
      - MYSQL_USER=elavon-user
      - MYSQL_PASSWORD=elavon-pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - "./docker/db/data:/var/lib/mysql:cached"

  redis:
    image: "jackthomasatl/docker-d8-redis:3.2"
    hostname: usbank-elavon-redis
    ports:
      - "6379:6379" # redis

  php:
    image: "jackthomasatl/docker-d8-php:5.6.36-fpm"
    environment:
      - MYSQL_HOSTNAME=mariadb # this matches the name:port of the DB container
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=eu-portal-dev
      - MYSQL_USER=elavon-user
      - MYSQL_PASSWORD=elavon-pass
      - REDIS_NODE=1
      - REDIS_HOST=redis     # this matches the name of the redis container
      - REDIS_DB=0           # which redis db to use (0 is the standard default)
      - HTTP_PROXY=$DOCKER_PROXY
      - http_proxy=$DOCKER_PROXY
      - HTTPS_PROXY=$DOCKER_PROXY
      - https_proxy=$DOCKER_PROXY
    ports:
      - "9001:9001" #xdebug
    volumes:
      - ./:/app
