#!/bin/bash

mysqldump \
  -h "$MYSQL_HOSTNAME" \
  -P "$MYSQL_PORT" \
  -u "$MYSQL_USER" \
  --password="$MYSQL_PASSWORD" \
  "$MYSQL_DATABASE" \
  --no-data \
    > /opt/sql/db.sql

mysqldump \
  --extended-insert=FALSE \
  -h "$MYSQL_HOSTNAME" \
  -P "$MYSQL_PORT" \
  -u "$MYSQL_USER" \
  --password="$MYSQL_PASSWORD" \
  "$MYSQL_DATABASE" \
  --no-create-info \
  --ignore-table="$MYSQL_DATABASE".cache \
  --ignore-table="$MYSQL_DATABASE".cache_admin_menu \
  --ignore-table="$MYSQL_DATABASE".cache_block \
  --ignore-table="$MYSQL_DATABASE".cache_bootstrap \
  --ignore-table="$MYSQL_DATABASE".cache_field \
  --ignore-table="$MYSQL_DATABASE".cache_filter \
  --ignore-table="$MYSQL_DATABASE".cache_form \
  --ignore-table="$MYSQL_DATABASE".cache_menu \
  --ignore-table="$MYSQL_DATABASE".cache_page \
  --ignore-table="$MYSQL_DATABASE".cache_path \
  --ignore-table="$MYSQL_DATABASE".cache_update \
  --ignore-table="$MYSQL_DATABASE".watchdog \
    >> /opt/sql/db.sql
